"""queue entry party_name phone notes

Revision ID: 0ce722e617b6
Revises: c1e0fbe457c9
Create Date: 2026-05-31 18:16:30.835798
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce722e617b6'
down_revision: Union[str, None] = 'c1e0fbe457c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_entries', sa.Column('party_name', sa.String(length=120), nullable=True))
    op.add_column('queue_entries', sa.Column('phone', sa.String(length=40), nullable=True))
    op.add_column('queue_entries', sa.Column('notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue_entries', 'notes')
    op.drop_column('queue_entries', 'phone')
    op.drop_column('queue_entries', 'party_name')
    # ### end Alembic commands ###
