"""initial schema

Revision ID: c1e0fbe457c9
Revises: 
Create Date: 2026-05-30 22:41:35.202989
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1e0fbe457c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_ja', sa.String(length=255), nullable=True),
    sa.Column('venue_type', sa.Enum('ramen', 'sushi', 'tempura', 'tonkatsu', 'yakiniku', 'kaiseki', 'cafe', 'other', name='venuetype'), nullable=False),
    sa.Column('avg_check_size', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.Column('avg_turn_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_gross', sa.Integer(), nullable=False),
    sa.Column('total_ifasto_fee', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'paid', name='invoicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_restaurant_id'), 'invoices', ['restaurant_id'], unique=False)
    op.create_table('queue_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.Enum('regular', 'premium', name='queueentrytype'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('waiting', 'seated', 'walked_away', name='queueentrystatus'), nullable=False),
    sa.Column('skip_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_entries_restaurant_id'), 'queue_entries', ['restaurant_id'], unique=False)
    op.create_table('service_windows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('days_of_week', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'manager', 'staff', name='userrole'), nullable=False),
    sa.Column('language_pref', sa.Enum('ja', 'en', name='languagepref'), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('venue_settings',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('max_premium_share', sa.Float(), nullable=False),
    sa.Column('price_floor', sa.Integer(), nullable=False),
    sa.Column('price_ceiling', sa.Integer(), nullable=False),
    sa.Column('max_party_size_eligible', sa.Integer(), nullable=False),
    sa.Column('large_party_cap_per_service', sa.Integer(), nullable=False),
    sa.Column('premium_paused', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('restaurant_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('queue_entry_id', sa.UUID(), nullable=False),
    sa.Column('gross_amount', sa.Integer(), nullable=False),
    sa.Column('restaurant_share', sa.Integer(), nullable=False),
    sa.Column('ifasto_fee', sa.Integer(), nullable=False),
    sa.Column('service_window_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['queue_entry_id'], ['queue_entries.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['service_window_id'], ['service_windows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queue_entry_id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_restaurant_id'), 'transactions', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_restaurant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('venue_settings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('service_windows')
    op.drop_index(op.f('ix_queue_entries_restaurant_id'), table_name='queue_entries')
    op.drop_table('queue_entries')
    op.drop_index(op.f('ix_invoices_restaurant_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
